#!/usr/bin/env bash
# Install nginx and use it
# can’t use systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hellow World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
