#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 1542-web-01 54.237.56.128:80 check
    server 1542-web-02 	34.224.16.76:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
